# Generated by Django 4.1.2 on 2023-02-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acceptance_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_function', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('type', models.CharField(default='Физлицо', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('min_duration', models.IntegerField(verbose_name='Минимальная длительность')),
                ('max_duration', models.IntegerField(verbose_name='Максимальна длительность')),
                ('type', models.CharField(max_length=255, verbose_name='Вид лизинга')),
                ('min_amount', models.FloatField(verbose_name='Минимальный размер')),
                ('max_amount', models.FloatField(verbose_name='Максимальный размер')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
            },
        ),
        migrations.CreateModel(
            name='Support_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('topic', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('phone_num', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.product', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Product_Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.product')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.acceptance_rule')),
            ],
        ),
        migrations.CreateModel(
            name='Interest_Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_more_than', models.IntegerField(verbose_name='Минимальный срок')),
                ('duration_less_than_or_equal', models.IntegerField(verbose_name='Максимальный срок')),
                ('rate', models.FloatField(verbose_name='Размер ставки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.product', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=40)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.clientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('rate', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('regular_payment_size', models.FloatField()),
                ('status', models.CharField(max_length=255)),
                ('payment_by_deed', models.CharField(max_length=255, null=True)),
                ('date_signed', models.DateField(null=True)),
                ('client_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.clientprofile')),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.document')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.product')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
                ('client_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.clientprofile')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='easyleasy2.product')),
            ],
        ),
    ]
